#!/bin/bash
# shellcheck disable=SC2148
# shellcheck disable=SC2034

# this file contains your service information

# (required) service identifier, which is used for creating its directories and
# logging. usually the same value as the service binary's name.
# (e.g. dnsmasq for /usr/bin/dnsmasq)
svc_id=$(
    # this evaluates to the name of the current directory!
    # you might think this is an overkill, but the script in log/run sourcing
    # the config causes it to be evaluated as "log"
    # shellcheck disable=SC2046
    basename $(dirname $(realpath "${BASH_SOURCE[0]}"))
)

# (required) absolute path to the service binary. (e.g. /usr/bin/dnsmasq)
svc_bin="/bin/bash"

# (optional) commandline args to be passed to the service program
svc_args=("-c" "pause")

# (optional) user and group you want this service to be ran as. leave unset to
# run as the current uid/gid. note that specifying these values implies using
# chpst, which requires root, for user services, comment these.
svc_user="$svc_id"
svc_group="$svc_id"

# (optional) if unset, not created and the svlogd process is not spawned
svc_log_dir="/var/log/$svc_id"

# (optional) custom user, group and permissions to create the log files and run
# the svlogd daemon as. if nothing specified, the current uid/gid is used.
# note that setting user/group requires root, because it invokes chpst.
svc_log_user="root"
svc_log_group="root"
svc_log_dir_perm="0750"

# (optional) exported variables are passed down to the chpst process.
export XDG_STATE_HOME="/var/lib"
export XDG_CACHE_HOME="/var/cache"
export XDG_DATA_HOME="/usr/share"
export XDG_CONFIG_HOME="/etc"
export HOME="$XDG_STATE_HOME/$svc_id"

# (optional) if svc_pwd is set, its value is passed as $PWD to chpst, otherwise
# dirname of the svc_bin is used (e.g. /bin for /bin/bash)
svc_pwd="$HOME"

# (optional) the env directory to pass to chpst.
svc_env_dir="/run/env-$svc_id/"

# (optional) an array of directories required to exist with the same user/group
# as the service process itself (svc_user, svc_group)
svc_dir_create=("$svc_pwd")

# (optional) custom permission to set on $svc_dir_create directories
svc_dir_perm="0750"

# note: modifications to the configuration variables won't persist in hooks

# (optional) for service daemons that do not make their service available
# immediately after starting, a check program can be added. The sv program will
# use this check program to better evaluate whether a service is working.
svc_hook_check() {
    # example for a mail service listening on localhost:25
    # exec nc -z localhost 25
    exit 0
}

# (optional) service start hook is executed before starting the service
svc_hook_start() {
    # if this service depends on other services (e.g. dbus and connmand):
    # sv start dbus connmand
    #
    # example for a webserver being ran under its own user with caps to listen
    # on privileged ports:
    # exec setcap 'cap_net_bind_service=+ep' "$svc_bin"
    #
    # another example is populating the env dir on-demand:
    # rm -rf "$svc_env_dir"
    # mkdir -p "$svc_env_dir"
    # echo -n "/bin" > "$svc_env_dir/PATH"
    exit 0
}

# (optional) executed when service is stopped. can place cleanup code in here.
svc_hook_finish() {
    # if another service depends on this service:
    # exec sv hup another_service
    exit 0
}
