#!/bin/bash
set -eu
exec 2>&1

# script exit codes:
# 111 -> chpst
# 100 -> chpst
# 200 -> $svc_bin doesn't exist
# 201 -> svc_hook_start
# 202 -> useradd
# 203 -> mkdir
# 204 -> chown
# 205 -> chmod

. ./conf

_print_log() {
    echo "[$svc_id] $*"
}

_create_dir() {
    local target_dir="$1"
    local target_perm="$2"
    local target_owner="$3"
    local target_group="$4"
    local current_owner
    local current_group
    local current_perm

    _print_log "[D] _create_dir($target_dir, $target_owner:$target_group," \
        "$target_perm)"

    if [ ! -d "$target_dir" ]; then
        mkdir --parents "$target_dir" ||
            exit 203
    fi

    current_owner=$(stat -c "%U" "$target_dir")
    current_group=$(stat -c "%G" "$target_dir")

    if [ "$current_owner" != "$target_owner" ] ||
        [ "$current_group" != "$target_group" ]; then
        chown "$target_owner:$target_group" "$target_dir" ||
            exit 204
    fi

    current_perm=$(stat -c "%a" "$target_dir")

    if [ "0$current_perm" -ne "$target_perm" ]; then
        chmod "$target_perm" "$target_dir" ||
            exit 205
    fi
}

# shellcheck disable=SC2128
: "$svc_bin"

: "${svc_dir_perm:=0750}"
: "${svc_pwd:=$(dirname "$svc_bin")}"

: "${svc_user:=$(id -un)}"
: "${svc_group:=$(id -gn)}"

_current_user=$(id -un)
_current_group=$(id -gn)
_start_hook_exit_code=0

if [ ! -f "$svc_bin" ]; then
    _print_log "[E] service binary not found ($svc_bin)"
    exit 200
fi

bash ./start || _start_hook_exit_code=$?

# shellcheck disable=SC2086
if [ $_start_hook_exit_code -ne 0 ]; then
    _print_log "[E] service start hook exited with code $_start_hook_exit_code"
    exit 201
fi

if declare -p svc_dir_create &> /dev/null; then
    for _svc_dir in "${svc_dir_create[@]}"; do
        _create_dir "$_svc_dir" "$svc_dir_perm" "$svc_user" "$svc_group"
    done
fi

if ! declare -p svc_args &> /dev/null; then
    declare -a svc_args
fi

if [ "$_current_user" != "$svc_user" ] ||
    [ "$_current_group" != "$svc_group" ]; then
    _chpst_args=(
        -v -0
        -C "$svc_pwd"
        -u "$svc_user:$svc_group"
    )

    if [ -n "${svc_env_dir:-}" ]; then
        _chpst_args+=(-e "$svc_env_dir")
    fi

    _print_log "[D] chpst ${_chpst_args[*]} $svc_bin ${svc_args[*]}"
    exec chpst "${_chpst_args[@]}" "$svc_bin" "${svc_args[@]}"
else
    # emulate the chpst behavior for its -e flag
    if [ -n "${svc_env_dir:-}" ] && [ -d "$svc_env_dir" ]; then
        shopt -s nullglob
        for file in "$svc_env_dir"/*; do
            [ -f "$file" ] || continue
            [ -s "$file" ] || continue

            _var=${file##*/}
            _val=$(< "$file")

            _print_log "[D] env['$_var']='$_val'"
            export "$_var=$_val"
        done
    fi

    # emulate chpst's -C flag
    cd "$svc_pwd"

    _print_log "[D] $svc_bin ${svc_args[*]}"
    exec "$svc_bin" "${svc_args[@]}"
fi
